trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-SPN-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group list -o table'